### ISSUE TITLE
Add to Plugins Directory

### ISSUE THREAD

**Issue by aljawaid** [skunkiferous/WeeklyRecurringTasks#1]
Hello, just found this through the forums... does this plugin work?  Ifso, would be great if you could add it to the Plugins Directory

**Comment by skunkiferous** [comment]
Hi. When I wrote it, it worked well. But in the end, I wanted it to organize "family tasks", and the family said "no".
So I didn't actually use it, and never updated it either.
Therefore, I would assume it does NOT work with the current version of Kanboard. Sorry.
If you, or someone you know, can code for Kanboard, it might still be less work to "fork" and fix this,
than to create a new plugin from scratch.

**Comment by aljawaid** [comment]
No worries, please add me to the repository... I will see if I can update it
